image: ghcr.io/home-assistant/{arch}-base
build_from:
  aarch64: "arm64v8/alpine:"
  armv7: "arm32v7/alpine:"
  armhf: "arm32v6/alpine:"
  amd64: "alpine:"
  i386: "i386/alpine:"
cosign:
  identity: https://github.com/home-assistant/docker-base/.*
args:
  BASHIO_VERSION: 0.17.5
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
  JEMALLOC_VERSION: 5.3.0
labels:
  io.hass.base.name: alpine
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
