version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    cooldown:
      default-days: 7
      exclude:
        - "home-assistant/*"
    open-pull-requests-limit: 10
