# This azure pipeline template build add-ons

parameters:
  version: ''
  name: ''
  args: ''

jobs:

- job: 'Python${{ parameters.name }}'
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags'), succeeded('Alpine'))
  dependsOn: 'Alpine'
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      amd64:
        buildArch: 'amd64'
      i386:
        buildArch: 'i386'
      armhf:
        buildArch: 'armhf'
      armv7:
        buildArch: 'armv7'
      aarch64:
        buildArch: 'aarch64'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --base-python ${{ parameters.version }} "--$(buildArch)" -t /data/python \
        --docker-hub homeassistant ${{ parameters.args }} \
        --release $(Build.SourceBranchName)
    displayName: 'Build Python ${{ parameters.version }} base-images'
