# This azure pipeline template build alpine base image

parameters:
- name:  version
  type: string
- name:  name
  type: string
- name:  args
  type: string
  default: ''
- name: builderArch
  type: object
  default:
  - amd64
  - i386
  - armhf
  - armv7
  - aarch64

jobs:

- job: 'Alpine${{ parameters.name }}'
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
     matrix:
      ${{ each arch in parameters.builderArch }}:
        ${{ arch }}:
          buildArch: ${{ arch }}
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) --base ${{ parameters.version }} \
        "--$(buildArch)" -t /data/alpine --docker-hub homeassistant \
        ${{ parameters.args }} --release $(Build.SourceBranchName)
    displayName: 'Build Alpine ${{ parameters.version }} base-images'
