image: ghcr.io/home-assistant/{arch}-base-ubuntu
build_from:
  aarch64: "arm64v8/ubuntu:"
  amd64: "ubuntu:"
cosign:
  identity: https://github.com/home-assistant/docker-base/.*
args:
  BASHIO_VERSION: 0.17.5
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.2.2.0
labels:
  io.hass.base.name: ubuntu
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
