image: ghcr.io/home-assistant/{arch}-base-debian
build_from:
  aarch64: "arm64v8/debian:"
  amd64: "debian:"
cosign:
  identity: https://github.com/home-assistant/docker-base/.*
args:
  BASHIO_VERSION: 0.17.5
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
labels:
  io.hass.base.name: debian
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
