# See here for image contents: https://github.com/devcontainers/images/blob/main/src/base-alpine/history/0.210.0.md

# [Choice] Alpine version: 3.19, 3.20, 3.21
ARG VARIANT="3.21"
FROM mcr.microsoft.com/devcontainers/base:0-alpine-${VARIANT}
