# See here for image contents: https://github.com/devcontainers/images/blob/main/src/base-alpine/history/0.210.0.md

# [Choice] Alpine version: 3.20, 3.21, 3.22
ARG VARIANT="3.22"
FROM mcr.microsoft.com/devcontainers/base:1-alpine-${VARIANT}
