image: homeassistant/{arch}-base-python
shadow_repository: ghcr.io/home-assistant
build_from:
  aarch64: "homeassistant/aarch64-base:"
  armv7: "homeassistant/armv7-base:"
  armhf: "homeassistant/armhf-base:"
  amd64: "homeassistant/amd64-base:"
  i386: "homeassistant/i386-base:"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  PYTHON_VERSION: 3.9.7
  PIP_VERSION: 20.2.4
  GPG_KEY: E3FF2839C048B25C084DEBE9B26995E310250568
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
