image: ghcr.io/home-assistant/{arch}-base-python
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:"
  armv7: "ghcr.io/home-assistant/armv7-base:"
  armhf: "ghcr.io/home-assistant/armhf-base:"
  amd64: "ghcr.io/home-assistant/amd64-base:"
  i386: "ghcr.io/home-assistant/i386-base:"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  PYTHON_VERSION: 3.9.17
  PIP_VERSION: 23.1.2
  GPG_KEY: E3FF2839C048B25C084DEBE9B26995E310250568
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
