image: homeassistant/{arch}-base-python
shadow_repository: ghcr.io/home-assistant
build_from:
  aarch64: "homeassistant/aarch64-base:"
  armv7: "homeassistant/armv7-base:"
  armhf: "homeassistant/armhf-base:"
  amd64: "homeassistant/amd64-base:"
  i386: "homeassistant/i386-base:"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  PYTHON_VERSION: 3.10.5
  PIP_VERSION: 22.2.0
  GPG_KEY: A035C8C19219BA821ECEA86B64E628F8D684696D
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
