image: ghcr.io/home-assistant/{arch}-base-raspbian
build_from:
  armhf: "tianon/raspbian:"
cosign:
  identity: https://github.com/home-assistant/docker-base/.*
args:
  BASHIO_VERSION: 0.15.0
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.5.0
labels:
  io.hass.base.name: raspbian
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
