image: homeassistant/{arch}-base-raspbian
shadow_repository: ghcr.io/home-assistant
build_from:
  armhf: "tianon/raspbian:"
codenotary:
  signer: notary@home-assistant.io
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 2.1.0.2
labels:
  io.hass.base.name: raspbian
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
