image: homeassistant/{arch}-base-python
shadow_repository: ghcr.io/home-assistant
build_from:
  aarch64: "homeassistant/aarch64-base:"
  armv7: "homeassistant/armv7-base:"
  armhf: "homeassistant/armhf-base:"
  amd64: "homeassistant/amd64-base:"
  i386: "homeassistant/i386-base:"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  PYTHON_VERSION: 3.7.12
  PIP_VERSION: 22.0.3
  GPG_KEY: 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
