image: ghcr.io/home-assistant/{arch}-base-python
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:"
  armv7: "ghcr.io/home-assistant/armv7-base:"
  armhf: "ghcr.io/home-assistant/armhf-base:"
  amd64: "ghcr.io/home-assistant/amd64-base:"
  i386: "ghcr.io/home-assistant/i386-base:"
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/docker-base/.*
args:
  PYTHON_VERSION: "3.13.8"
  PIP_VERSION: "25.2"
  CERT_IDENTITY: thomas@python.org
  CERT_OIDC_ISSUER: https://accounts.google.com
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
